// SkillMatch — Sample Data
// Adapted from India Runs candidate/JD schema to student opportunity context

const daysFromNow = (n) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

const OPPORTUNITIES = [
  {
    id: 1,
    title: "Google Summer of Code 2025",
    org: "Google",
    orgInitials: "G",
    orgColor: "#4285f4",
    type: "Open Source",
    typeKey: "opensource",
    description: "Contribute to open source projects under Google's mentorship. Get paid to code and build your portfolio with real-world impact used by millions.",
    longDescription: "Google Summer of Code is a global program focused on bringing more developers into open source software development. Students work with an open source organization on a 3-month programming project during the summer. You'll be paired with a mentor from the organization, giving you real-world development experience.",
    requiredSkills: ["Python", "Git", "Algorithms"],
    niceToHaveSkills: ["JavaScript", "C++", "Machine Learning", "Open Source"],
    eligibleYears: [1, 2, 3, 4],
    eligibleBranches: ["All"],
    minCGPA: 6.0,
    stipend: "₹1,20,000",
    deadline: daysFromNow(5),
    duration: "3 months",
    mode: "Remote",
    location: "Remote (Global)",
    tags: ["coding", "mentorship", "open-source", "paid"],
    difficulty: "Intermediate",
    applicants: 12400,
    featured: true
  },
  {
    id: 2,
    title: "Microsoft Explore Internship",
    org: "Microsoft",
    orgInitials: "MS",
    orgColor: "#00a4ef",
    type: "Internship",
    typeKey: "internship",
    description: "A 12-week summer internship at Microsoft for pre-final year students. Work on real products like Azure, Teams, or Xbox alongside top engineers.",
    longDescription: "The Microsoft Explore Internship is a 12-week summer program for students who are interested in exploring a career in software engineering. You will be assigned to a Microsoft product team, where you'll gain hands-on engineering experience and work with a mentor.",
    requiredSkills: ["C++", "Data Structures", "Problem Solving"],
    niceToHaveSkills: ["Python", "Cloud", "System Design", "Java"],
    eligibleYears: [2, 3],
    eligibleBranches: ["CSE", "IT", "ECE"],
    minCGPA: 7.5,
    stipend: "₹1,60,000/month",
    deadline: daysFromNow(12),
    duration: "12 weeks",
    mode: "Hybrid",
    location: "Hyderabad / Bangalore",
    tags: ["internship", "product", "premium", "paid"],
    difficulty: "Hard",
    applicants: 45000,
    featured: true
  },
  {
    id: 3,
    title: "Smart India Hackathon 2025",
    org: "Ministry of Education",
    orgInitials: "SIH",
    orgColor: "#ff6b35",
    type: "Hackathon",
    typeKey: "hackathon",
    description: "India's biggest hackathon — solve real government challenges. 36-hour sprint with ₹1L prize pool. Team of 6. Every engineering student is eligible.",
    longDescription: "Smart India Hackathon (SIH) is a nationwide initiative to provide students a platform where they can propose solutions to some of pressing problems we face in our daily lives, and thus inculcate a culture of product innovation.",
    requiredSkills: ["Problem Solving", "Team Work"],
    niceToHaveSkills: ["Web Development", "Machine Learning", "IoT", "Blockchain", "Python"],
    eligibleYears: [1, 2, 3, 4],
    eligibleBranches: ["All"],
    minCGPA: 0,
    stipend: "₹1,00,000 prize",
    deadline: daysFromNow(2),
    duration: "36 hours",
    mode: "Offline",
    location: "Pan India — Multiple Venues",
    tags: ["hackathon", "government", "prize", "team", "national"],
    difficulty: "Beginner",
    applicants: 5200,
    featured: true,
    urgent: true
  },
  {
    id: 4,
    title: "Adobe GenAI Hackathon",
    org: "Adobe",
    orgInitials: "Ad",
    orgColor: "#e1251b",
    type: "Hackathon",
    typeKey: "hackathon",
    description: "Build creative AI tools using Adobe's cutting-edge APIs. Focus on generative AI for design, video editing, and creative content workflows.",
    longDescription: "Adobe's GenAI Hackathon challenges you to reimagine creativity using AI. Use Adobe's Firefly, Express, and Creative Cloud APIs to build tools that augment human creativity. The best projects get featured at Adobe MAX and could become real products.",
    requiredSkills: ["Python", "Machine Learning", "APIs"],
    niceToHaveSkills: ["Computer Vision", "NLP", "React", "UI/UX", "JavaScript"],
    eligibleYears: [2, 3, 4],
    eligibleBranches: ["CSE", "IT", "Design"],
    minCGPA: 6.5,
    stipend: "₹75,000 prize",
    deadline: daysFromNow(8),
    duration: "48 hours",
    mode: "Online",
    location: "Remote",
    tags: ["hackathon", "AI", "creative", "prize", "generative"],
    difficulty: "Intermediate",
    applicants: 3200,
    featured: false
  },
  {
    id: 5,
    title: "Goldman Sachs Engineering Campus Hire",
    org: "Goldman Sachs",
    orgInitials: "GS",
    orgColor: "#6699cc",
    type: "Internship",
    typeKey: "internship",
    description: "10-week summer internship in technology division. Work on trading platforms, risk management systems, and financial software at global scale.",
    longDescription: "Goldman Sachs Technology internships put you at the center of finance and technology. You'll work on the platforms that power billions in daily transactions, collaborating with some of the brightest minds in the industry.",
    requiredSkills: ["Java", "Data Structures", "Algorithms", "Problem Solving"],
    niceToHaveSkills: ["Python", "SQL", "System Design", "Finance", "C++"],
    eligibleYears: [3],
    eligibleBranches: ["CSE", "IT", "ECE", "Mathematics"],
    minCGPA: 8.0,
    stipend: "₹2,00,000/month",
    deadline: daysFromNow(20),
    duration: "10 weeks",
    mode: "In-Office",
    location: "Bangalore",
    tags: ["internship", "finance", "premium", "paid", "quant"],
    difficulty: "Hard",
    applicants: 28000,
    featured: false
  },
  {
    id: 6,
    title: "Flipkart Grid 6.0",
    org: "Flipkart",
    orgInitials: "FK",
    orgColor: "#F9A825",
    type: "Hackathon",
    typeKey: "hackathon",
    description: "Flipkart's flagship engineering challenge. Solve e-commerce problems at massive scale. Tracks: Software, Robotics, AI/ML. PPO for winners.",
    longDescription: "Flipkart GRID is one of India's most prestigious engineering competitions. Compete with the best minds to solve some of the most challenging e-commerce problems at a scale used by hundreds of millions of customers.",
    requiredSkills: ["Problem Solving", "Algorithms", "Data Structures"],
    niceToHaveSkills: ["Machine Learning", "System Design", "SQL", "Python", "Java"],
    eligibleYears: [2, 3, 4],
    eligibleBranches: ["CSE", "IT", "ECE"],
    minCGPA: 7.0,
    stipend: "₹50,000 + PPO Opportunity",
    deadline: daysFromNow(15),
    duration: "Multiple rounds",
    mode: "Online + Offline Final",
    location: "Bangalore (Final)",
    tags: ["hackathon", "e-commerce", "PPO", "prize", "scale"],
    difficulty: "Hard",
    applicants: 150000,
    featured: true
  },
  {
    id: 7,
    title: "MLH Fellowship — Open Source Track",
    org: "Major League Hacking",
    orgInitials: "MLH",
    orgColor: "#f0a500",
    type: "Fellowship",
    typeKey: "fellowship",
    description: "A 12-week remote paid fellowship working with top open source organizations. Build real features, get mentorship, earn a stipend.",
    longDescription: "The MLH Fellowship is an alternative to the traditional internship for aspiring software engineers. You'll contribute to open source projects used by millions of developers and companies worldwide, guided by experienced mentors.",
    requiredSkills: ["Git", "Open Source", "Problem Solving"],
    niceToHaveSkills: ["JavaScript", "Python", "React", "Node.js", "TypeScript"],
    eligibleYears: [1, 2, 3, 4],
    eligibleBranches: ["All"],
    minCGPA: 0,
    stipend: "$5,000 USD",
    deadline: daysFromNow(30),
    duration: "12 weeks",
    mode: "Remote",
    location: "Remote (Global)",
    tags: ["fellowship", "open-source", "paid", "mentorship", "international"],
    difficulty: "Intermediate",
    applicants: 8700,
    featured: false
  },
  {
    id: 8,
    title: "ISRO Young Scientist Programme",
    org: "ISRO",
    orgInitials: "🚀",
    orgColor: "#ff8c42",
    type: "Research",
    typeKey: "research",
    description: "Residential programme at ISRO centers for top students. Work alongside real space scientists on satellite and launch vehicle projects.",
    longDescription: "ISRO's Young Scientist Programme (YUVIKA) is designed to impart knowledge on space technology, space science and space applications to school students primarily to attract young talents to pursue a career in space science and technology.",
    requiredSkills: ["Physics", "Mathematics", "Problem Solving"],
    niceToHaveSkills: ["Python", "MATLAB", "C", "Signal Processing", "Embedded Systems"],
    eligibleYears: [1, 2],
    eligibleBranches: ["CSE", "ECE", "Mechanical", "Aerospace", "Physics"],
    minCGPA: 8.5,
    stipend: "Fully Funded (Travel + Stay)",
    deadline: daysFromNow(45),
    duration: "2 weeks",
    mode: "Offline",
    location: "Bangalore / Thiruvananthapuram",
    tags: ["research", "space", "residential", "funded", "science"],
    difficulty: "Hard",
    applicants: 50000,
    featured: false
  },
  {
    id: 9,
    title: "Walmart Global Tech Hackathon",
    org: "Walmart",
    orgInitials: "W",
    orgColor: "#0071ce",
    type: "Hackathon",
    typeKey: "hackathon",
    description: "Build innovative retail tech solutions. Tracks: Supply Chain AI, Customer Experience, Sustainability. Top teams get fast-tracked for interviews.",
    longDescription: "Walmart Global Tech Hackathon challenges you to reimagine retail at scale. With 100M+ customers and petabytes of data, the problems here are genuinely hard. Build something real and get noticed by world-class engineers.",
    requiredSkills: ["Web Development", "Problem Solving"],
    niceToHaveSkills: ["React", "Node.js", "Python", "Machine Learning", "SQL", "Cloud"],
    eligibleYears: [2, 3, 4],
    eligibleBranches: ["CSE", "IT"],
    minCGPA: 7.0,
    stipend: "₹1,50,000 prize",
    deadline: daysFromNow(7),
    duration: "24 hours",
    mode: "Hybrid",
    location: "Bangalore + Remote",
    tags: ["hackathon", "retail", "AI", "prize", "scale"],
    difficulty: "Intermediate",
    applicants: 25000,
    featured: false
  },
  {
    id: 10,
    title: "Amazon ML Summer School",
    org: "Amazon",
    orgInitials: "Az",
    orgColor: "#ff9900",
    type: "Research",
    typeKey: "research",
    description: "6-day virtual school on supervised learning, NLP, computer vision, and recommendation systems — taught by Amazon scientists. Free with certificate.",
    longDescription: "Amazon ML Summer School is a prestigious program that gives students a comprehensive overview of machine learning techniques used in industry. Sessions are taught by Amazon scientists working on products like Alexa, Prime, and AWS.",
    requiredSkills: ["Python", "Mathematics", "Statistics"],
    niceToHaveSkills: ["Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "Linear Algebra"],
    eligibleYears: [2, 3, 4],
    eligibleBranches: ["CSE", "IT", "Mathematics", "Statistics"],
    minCGPA: 7.0,
    stipend: "Free (Certificate)",
    deadline: daysFromNow(25),
    duration: "6 days",
    mode: "Online",
    location: "Remote",
    tags: ["learning", "ML", "Amazon", "certificate", "AI"],
    difficulty: "Intermediate",
    applicants: 95000,
    featured: false
  },
  {
    id: 11,
    title: "HackWithInfy — National Hackathon",
    org: "Infosys",
    orgInitials: "In",
    orgColor: "#007cc3",
    type: "Hackathon",
    typeKey: "hackathon",
    description: "National level hackathon by Infosys. Build solutions using emerging tech. Winners receive Pre-Placement Offers and ₹2L prize money.",
    longDescription: "HackWithInfy is Infosys's flagship national hackathon open to all engineering students. It's one of the few hackathons that directly converts winners into Infosys systems engineers with a Pre-Placement Offer (PPO).",
    requiredSkills: ["Problem Solving", "Any Programming Language"],
    niceToHaveSkills: ["Java", "Python", "Cloud", "AI/ML", "JavaScript"],
    eligibleYears: [3, 4],
    eligibleBranches: ["CSE", "IT", "ECE", "Mechanical", "Civil"],
    minCGPA: 6.0,
    stipend: "₹2,00,000 prize + PPO",
    deadline: daysFromNow(18),
    duration: "48 hours",
    mode: "Online",
    location: "Remote",
    tags: ["hackathon", "PPO", "prize", "national", "placement"],
    difficulty: "Beginner",
    applicants: 75000,
    featured: false
  },
  {
    id: 12,
    title: "GitHub Campus Expert Program",
    org: "GitHub",
    orgInitials: "GH",
    orgColor: "#2dba4e",
    type: "Fellowship",
    typeKey: "fellowship",
    description: "Become a GitHub Campus Expert — build your college's developer community with GitHub's backing, resources, and global network.",
    longDescription: "GitHub Campus Experts are student leaders that strive to build diverse and inclusive spaces to learn skills, share their experiences, and build projects together. As an Expert, you get access to training, resources, and GitHub's global network.",
    requiredSkills: ["Git", "Communication", "Leadership"],
    niceToHaveSkills: ["Public Speaking", "Community Building", "Open Source", "Event Management"],
    eligibleYears: [1, 2, 3, 4],
    eligibleBranches: ["All"],
    minCGPA: 0,
    stipend: "Swag + GitHub Credits + Benefits",
    deadline: daysFromNow(60),
    duration: "Ongoing",
    mode: "Remote",
    location: "Your Campus",
    tags: ["community", "leadership", "github", "open-source", "network"],
    difficulty: "Beginner",
    applicants: 2300,
    featured: false
  }
];

const ALL_SKILLS = [
  // Programming Languages
  "Python", "JavaScript", "Java", "C++", "C", "TypeScript", "Go", "Rust", "MATLAB",
  // Frontend
  "React", "Vue.js", "HTML/CSS", "Tailwind CSS", "Next.js",
  // Backend
  "Node.js", "Django", "FastAPI", "Express.js", "Spring Boot",
  // CS Fundamentals
  "Data Structures", "Algorithms", "Problem Solving", "System Design", "OOP",
  // Data & ML
  "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "NLP",
  "Computer Vision", "Statistics", "Mathematics", "Linear Algebra",
  // Databases
  "SQL", "MongoDB", "PostgreSQL", "Redis", "Firebase",
  // Cloud & DevOps
  "Cloud", "AWS", "Azure", "GCP", "Docker", "Kubernetes", "Linux",
  // Tools
  "Git", "Open Source", "Figma", "UI/UX",
  // Domain
  "Signal Processing", "IoT", "Blockchain", "Embedded Systems",
  "Physics", "Aerospace", "Finance",
  // Soft Skills
  "Communication", "Leadership", "Team Work", "Problem Solving",
  "Public Speaking", "Community Building", "Event Management", "Presentation",
  "APIs", "Web Development", "Any Programming Language"
];

const BRANCHES = [
  "CSE", "IT", "ECE", "EEE", "Mechanical",
  "Civil", "Aerospace", "Mathematics", "Statistics", "Physics", "Design", "Other"
];

const INTERESTS = [
  "AI/ML", "Web Development", "Open Source", "Hackathons",
  "Research", "FinTech", "Cloud Computing", "Cybersecurity",
  "Mobile Development", "Data Science", "Blockchain", "IoT",
  "Robotics", "Space Tech", "Game Development", "Community Building"
];

const OPPORTUNITY_TYPES = [
  { key: "all", label: "All Types" },
  { key: "hackathon", label: "Hackathon" },
  { key: "internship", label: "Internship" },
  { key: "fellowship", label: "Fellowship" },
  { key: "research", label: "Research" },
  { key: "opensource", label: "Open Source" }
];
